package io.github.jaknndiius.schoolapp.preset

enum class TimetableFragmentType {
    LIST_FRAGMENT,
    SETTING_FRAGMENT,
    MANAGE_SUBJECT_FRAGMENT,
    SUBJECT_EDITOR_FRAGMENT,
    CHANGE_TIMETABLE_FRAGMENT,
    EXAM_SETTER_FRAGMENT,
    EXAM_UPDATER_FRAGMENT,
    EXAM_TIMETABLE_CHANGER_FRAGMENT
}